// Fresh independent enumerator: all eligible STS row pairs, every trade mask,
// all affine corner parameters over odd primes <=61. No stored results imported.
#include <algorithm>
#include <array>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <numeric>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>
using namespace std;using Square=vector<vector<int>>;using Type=vector<int>;using Spec=map<Type,int>;
void req(bool b,const string&s){if(!b)throw runtime_error(s);}
vector<Type> cycles(const vector<int>&p){vector<Type>ans;vector<bool>seen(p.size());for(int i=0;i<(int)p.size();i++)if(!seen[i]){Type c;int j=i;while(!seen[j]){seen[j]=true;c.push_back(j);j=p[j];}req(j==i,"nonpermutation");ans.push_back(c);}return ans;}
vector<int> inv(const vector<int>&p){vector<int>q(p.size());for(int i=0;i<(int)p.size();i++)q[p[i]]=i;return q;}
vector<Type> rowcycles(const Square&L,int a,int b){auto ib=inv(L[b]);vector<int>p(L.size());for(int i=0;i<(int)L.size();i++)p[i]=ib[L[a][i]];return cycles(p);}
struct Scan{string pat;Spec spectrum;array<int,3>I{0,0,0};};
Scan scan(const Square&L){int n=L.size();for(int r=0;r<n;r++){set<int>a,b;for(int c=0;c<n;c++){req(L[r][c]>=0&&L[r][c]<n,"value");a.insert(L[r][c]);b.insert(L[c][r]);}req((int)a.size()==n&&(int)b.size()==n,"Latin");}Scan out;for(int v=0;v<3;v++){Square f(n,vector<int>(n)),fi;for(int r=0;r<n;r++)for(int c=0;c<n;c++){int s=L[r][c];if(v==0)f[r][c]=s;if(v==1)f[c][r]=s;if(v==2)f[s][c]=r;}for(auto&p:f)fi.push_back(inv(p));bool bad=false;for(int a=0;a<n;a++)for(int b=a+1;b<n;b++){vector<int>p(n);for(int x=0;x<n;x++)p[x]=fi[b][f[a][x]];Type t;for(auto&C:cycles(p)){int k=C.size();req(k>1,"fixed point");t.push_back(k);bad|=k%2;out.I[v]+=(k==2);}sort(t.begin(),t.end());out.spectrum[t]++;}out.pat+=bad?'T':'F';}req(out.I[0]==out.I[1]&&out.I[0]==out.I[2],"intercalates");return out;}
Square sts(){Square L(20,vector<int>(20,-1));int starters[11][3]={{18,0,3},{18,6,9},{18,12,15},{0,1,6},{0,2,13},{6,7,13},{6,8,4},{12,13,8},{12,14,4},{0,9,12},{0,7,15}};set<Type>triples;for(auto&s:starters)for(int k=0;k<6;k++){Type t;for(int x:s)t.push_back(x==18?18:x/6*6+(x%6+k)%6);sort(t.begin(),t.end());triples.insert(t);}req(triples.size()==57,"STS blocks");for(auto t:triples)do{req(L[t[0]][t[1]]<0||L[t[0]][t[1]]==t[2],"STS pair");L[t[0]][t[1]]=t[2];}while(next_permutation(t.begin(),t.end()));for(int x=0;x<20;x++)L[x][19]=L[19][x]=x;for(int x=0;x<19;x++)L[x][x]=19;return L;}
int mod(int x,int p){return (x%p+p)%p;}int im(int a,int p){for(int i=1;i<p;i++)if(a*i%p==1)return i;throw runtime_error("inverse");}
Square affine(int p,int a){Square L(p+1,vector<int>(p+1));for(int r=0;r<=p;r++)for(int c=0;c<=p;c++)L[r][c]=r==p?c:c==p?r:r==c?p:mod(a*r+(1-a)*c,p);return L;}
Square prolong(int p,int a){Square L(p+1,vector<int>(p+1));for(int r=0;r<=p;r++)for(int c=0;c<=p;c++)L[r][c]=r==p?(c==p?p:mod((a+1)*im(a,p)*c,p)):c==p?mod((a+1)*r,p):c==a*r%p?p:mod(r+c,p);return L;}
Square corner(Square L){int p=L.size()-1;swap(L[0][0],L[0][p]);swap(L[p][0],L[p][p]);return L;}
vector<int> minor(const Square&L){array<uint64_t,58>b{};vector<int>cells;for(int r=0;r<20;r++)for(int c=0;c<20;c++){int s=L[r][c];uint64_t x=1ULL<<r;if(c<19)x^=1ULL<<(20+c);if(s<19)x^=1ULL<<(39+s);while(x){int k=63-__builtin_clzll(x);if(b[k])x^=b[k];else{b[k]=x;cells.push_back(20*r+c);break;}}}req(cells.size()==58,"rank defect");return cells;}
void jv(ostream&o,const vector<int>&v){o<<'[';for(size_t i=0;i<v.size();i++){if(i)o<<',';o<<v[i];}o<<']';}
void record(ostream&o,const Square&L,const Scan&s,const string&origin,int a,int b,int mask){o<<"{\"origin\":\""<<origin<<"\",\"a\":"<<a<<",\"b\":"<<b<<",\"mask\":"<<mask<<",\"intercalates\":"<<s.I[0]<<",\"table\":[";for(int r=0;r<20;r++){if(r)o<<',';jv(o,L[r]);}o<<"],\"minor_cells\":";jv(o,minor(L));o<<",\"spectrum\":[";bool fst=true;for(auto&[t,k]:s.spectrum){if(!fst)o<<',';fst=false;o<<'[';jv(o,t);o<<','<<k<<']';}o<<"]}\n";}
int main(int argc,char**argv){try{req(argc==2,"usage outdir");string dir=argv[1];ofstream reps(dir+"/expanded_representatives.jsonl"),sum(dir+"/expanded_summary.json"),cp(dir+"/corner_parameters.csv");req(reps.good()&&sum.good()&&cp.good(),"cannot open result files");auto L=sts();set<Spec>specs;map<string,int>patterns;int pairs=0,masks=0,minI=9999,maxI=0;cp<<"p,a,before,after,I_before,I_after,generic,empty_hole_count\n";for(int a=0;a<20;a++)for(int b=a+1;b<20;b++){auto cy=rowcycles(L,a,b);if(cy.size()!=10||any_of(cy.begin(),cy.end(),[](auto&C){return C.size()!=2;}))continue;pairs++;int fff=0;for(int mask=0;mask<1024;mask++){Square K=L;for(int bit=0;bit<10;bit++)if(mask>>bit&1)for(int c:cy[bit])swap(K[a][c],K[b][c]);auto s=scan(K);masks++;patterns[s.pat]++;if(s.pat=="FFF"){fff++;if(specs.insert(s.spectrum).second){minI=min(minI,s.I[0]);maxI=max(maxI,s.I[0]);record(reps,K,s,"steiner_mask",a,b,mask);}}}cerr<<"row pair "<<a<<','<<b<<": FFF "<<fff<<", cumulative spectra "<<specs.size()<<'\n';}int steiner=specs.size();for(int a:{2,8}){auto K=affine(19,a);auto s=scan(K);req(s.pat=="FFF","control FFF");req(specs.insert(s.spectrum).second,"control collision");record(reps,K,s,"affine_Q",19,a,-1);}auto U=corner(prolong(19,7));auto us=scan(U);req(us.pat=="FFF"&&us.I[0]==1,"corner witness");req(specs.insert(us.spectrum).second,"corner collision");record(reps,U,us,"corner_P",19,7,-1);
int tested=0,generic=0;map<int,int>fffcount;for(int p=3;p<=61;p+=2){bool prime=true;for(int d=2;d*d<=p;d++)if(p%d==0)prime=false;if(!prime)continue;for(int a=1;a<p-1;a++){auto P=prolong(p,a);auto K=corner(P);auto s=scan(P),t=scan(K);req(s.pat==t.pat,"PATTERN p="+to_string(p)+" a="+to_string(a));bool gen=p>=5&&a!=1&&a!=p-2&&a!=mod(-im(2,p),p);int holes=0;if(gen){req(s.I[0]==p&&t.I[0]==1,"INTERCALATE");for(int r=1;r<p;r++){int c=p-r;set<int>R,C;for(int x=1;x<p;x++){R.insert(K[r][x]);C.insert(K[x][c]);}bool empty=true;for(int v=1;v<p;v++)if(!R.count(v)&&!C.count(v))empty=false;req(empty,"hole domain");holes++;}generic++;}tested++;fffcount[p]+=(t.pat=="FFF");cp<<p<<','<<a<<','<<s.pat<<','<<t.pat<<','<<s.I[0]<<','<<t.I[0]<<','<<gen<<','<<holes<<'\n';}}
sum<<"{\"row_pairs\":"<<pairs<<",\"mask_instances\":"<<masks<<",\"patterns\":{";bool first=true;for(auto&[s,k]:patterns){if(!first)sum<<',';first=false;sum<<'\"'<<s<<"\":"<<k;}sum<<"},\"steiner_spectra\":"<<steiner<<",\"all_selected_spectra\":"<<specs.size()<<",\"steiner_intercalate_min\":"<<minI<<",\"steiner_intercalate_max\":"<<maxI<<",\"corner_parameters_tested\":"<<tested<<",\"generic_parameters_tested\":"<<generic<<",\"corner_failures\":0,\"p17_fff_parameters\":"<<fffcount[17]<<"}\n";req(pairs==22&&masks==22528&&patterns["FFF"]==19480&&steiner==1700&&specs.size()==1703,"enumeration discrepancy");return 0;}catch(const exception&e){cerr<<e.what()<<'\n';return 1;}}
